### ISSUE TITLE
Some vars not defined in config.py

### ISSUE THREAD

**Issue by coolsober** [evgps/a3c_trading#2]
In A3C_training.py  

from configs import TRAIN_DATA, LOAD_MODEL, LR, FRAMES_STACKED, NUM_WORKERS, MODEL_DIR

But I can't find the TRAIN_DATA, FRAMES_STACKED and NUM_WORKERS in configs.py

**Comment by coolsober** [comment]
Defined by myself.

**Comment by personal-coding** [comment]
@coolsober How did you define the variables? The one that is tripping me up is the TRAIN_DATA variable.

**Comment by ZeroNilZero** [comment]
@coolsober what did you set for FRAMES_STACKED? and  what is use of it?
